window.ESPN_TEAMS=[
  {id:"22",displayName:"Arizona Cardinals",shortDisplayName:"Cardinals",abbreviation:"ARI",conference:"NFC",division:"NFC West"},
  {id:"1",displayName:"Atlanta Falcons",shortDisplayName:"Falcons",abbreviation:"ATL",conference:"NFC",division:"NFC South"},
  {id:"33",displayName:"Baltimore Ravens",shortDisplayName:"Ravens",abbreviation:"BAL",conference:"AFC",division:"AFC North"},
  {id:"2",displayName:"Buffalo Bills",shortDisplayName:"Bills",abbreviation:"BUF",conference:"AFC",division:"AFC East"},
  {id:"29",displayName:"Carolina Panthers",shortDisplayName:"Panthers",abbreviation:"CAR",conference:"NFC",division:"NFC South"},
  {id:"3",displayName:"Chicago Bears",shortDisplayName:"Bears",abbreviation:"CHI",conference:"NFC",division:"NFC North"},
  {id:"4",displayName:"Cincinnati Bengals",shortDisplayName:"Bengals",abbreviation:"CIN",conference:"AFC",division:"AFC North"},
  {id:"5",displayName:"Cleveland Browns",shortDisplayName:"Browns",abbreviation:"CLE",conference:"AFC",division:"AFC North"},
  {id:"6",displayName:"Dallas Cowboys",shortDisplayName:"Cowboys",abbreviation:"DAL",conference:"NFC",division:"NFC East"},
  {id:"7",displayName:"Denver Broncos",shortDisplayName:"Broncos",abbreviation:"DEN",conference:"AFC",division:"AFC West"},
  {id:"8",displayName:"Detroit Lions",shortDisplayName:"Lions",abbreviation:"DET",conference:"NFC",division:"NFC North"},
  {id:"9",displayName:"Green Bay Packers",shortDisplayName:"Packers",abbreviation:"GB",conference:"NFC",division:"NFC North"},
  {id:"34",displayName:"Houston Texans",shortDisplayName:"Texans",abbreviation:"HOU",conference:"AFC",division:"AFC South"},
  {id:"11",displayName:"Indianapolis Colts",shortDisplayName:"Colts",abbreviation:"IND",conference:"AFC",division:"AFC South"},
  {id:"30",displayName:"Jacksonville Jaguars",shortDisplayName:"Jaguars",abbreviation:"JAX",conference:"AFC",division:"AFC South"},
  {id:"12",displayName:"Kansas City Chiefs",shortDisplayName:"Chiefs",abbreviation:"KC",conference:"AFC",division:"AFC West"},
  {id:"13",displayName:"Las Vegas Raiders",shortDisplayName:"Raiders",abbreviation:"LV",conference:"AFC",division:"AFC West"},
  {id:"24",displayName:"Los Angeles Chargers",shortDisplayName:"Chargers",abbreviation:"LAC",conference:"AFC",division:"AFC West"},
  {id:"14",displayName:"Los Angeles Rams",shortDisplayName:"Rams",abbreviation:"LAR",conference:"NFC",division:"NFC West"},
  {id:"15",displayName:"Miami Dolphins",shortDisplayName:"Dolphins",abbreviation:"MIA",conference:"AFC",division:"AFC East"},
  {id:"16",displayName:"Minnesota Vikings",shortDisplayName:"Vikings",abbreviation:"MIN",conference:"NFC",division:"NFC North"},
  {id:"17",displayName:"New England Patriots",shortDisplayName:"Patriots",abbreviation:"NE",conference:"AFC",division:"AFC East"},
  {id:"18",displayName:"New Orleans Saints",shortDisplayName:"Saints",abbreviation:"NO",conference:"NFC",division:"NFC South"},
  {id:"19",displayName:"New York Giants",shortDisplayName:"Giants",abbreviation:"NYG",conference:"NFC",division:"NFC East"},
  {id:"20",displayName:"New York Jets",shortDisplayName:"Jets",abbreviation:"NYJ",conference:"AFC",division:"AFC East"},
  {id:"21",displayName:"Philadelphia Eagles",shortDisplayName:"Eagles",abbreviation:"PHI",conference:"NFC",division:"NFC East"},
  {id:"23",displayName:"Pittsburgh Steelers",shortDisplayName:"Steelers",abbreviation:"PIT",conference:"AFC",division:"AFC North"},
  {id:"25",displayName:"San Francisco 49ers",shortDisplayName:"49ers",abbreviation:"SF",conference:"NFC",division:"NFC West"},
  {id:"26",displayName:"Seattle Seahawks",shortDisplayName:"Seahawks",abbreviation:"SEA",conference:"NFC",division:"NFC West"},
  {id:"27",displayName:"Tampa Bay Buccaneers",shortDisplayName:"Buccaneers",abbreviation:"TB",conference:"NFC",division:"NFC South"},
  {id:"10",displayName:"Tennessee Titans",shortDisplayName:"Titans",abbreviation:"TEN",conference:"AFC",division:"AFC South"},
  {id:"28",displayName:"Washington Commanders",shortDisplayName:"Commanders",abbreviation:"WSH",conference:"NFC",division:"NFC East"}
];
